---
title: "test_3d_legend"
output: html_document
date: '2023-07-26'
---

```{r}

library(ggplot2)
library(tidyr)
library(data.table)
library(ggnewscale)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```


```{r}
## read in dfs containing information of distance to the nearest pav and conserved genes for all genes for both wheat and rice blast
df_distance_info_wheat_blast <-data.frame(fread(
  '../../pav_newest_wheat_blast_all/deletion_statistics/gene_deletion_distance_info.txt'))

df_distance_info_wheat_blast$host = "wheat"
  
df_distance_info_rice_blast <- data.frame(fread(
  '../../pav_newest_gladieux_only_fungap/deletion_statistics/gene_deletion_distance_info.txt'))

df_distance_info_rice_blast$host = "rice"

df_distance_info <- rbind(df_distance_info_rice_blast, df_distance_info_wheat_blast)

rm(df_distance_info_wheat_blast)

rm(df_distance_info_rice_blast)


colnames(df_distance_info) <- c("scaffold", "start", "end", "orientation", "id",
                            "lineage_conserved", "lineage_pav",
                            "genome", "lineage",
                            'pav_gene_distance_upstream', 'pav_gene_distance_downstream', 'pav_gene_distance_closest',
                            'conserved_gene_distance_upstream', 'conserved_gene_distance_downstream', 'conserved_gene_distance_closest',
                            'enough_space_pav', 'enough_space_conserved',
                            'pav_nearby', 'conserved_nearby', 'host'
                            )

## remove lineage 4 as pav genes are not as well defined there
df_distance_info <- df_distance_info[df_distance_info$lineage != 4,]

```

```{r}

print('DOWN SAMPLE FOR TESTS')

library(dplyr)

df_distance_info <- df_distance_info %>% sample_frac(0.01)

```



```{r}

plot_columns_list = list(
  c("pav_gene_distance_upstream", "pav_gene_distance_downstream"),
  c("conserved_gene_distance_upstream", "conserved_gene_distance_downstream")
)

axis_labels = c(
  "PAV Gene",
  "Conserved Gene"
)

```

```{r}

for (i in seq(from=1, to=length(plot_columns_list))){
  
  plot_columns = unlist(plot_columns_list[i])
  
  axis_label = axis_labels[i]
  
  # exclude other genes
  df <- df_distance_info[df_distance_info$lineage_pav == TRUE | df_distance_info$lineage_conserved == TRUE,
                         c('lineage_conserved', 'lineage_pav')]
  df[df==TRUE] <- 1
  df[df==FALSE] <- 0
  
  w <- which(df==1, arr.ind = T)
  df$gene_type <- toupper(names(df)[max.col(df)])
  
  df[df=="LINEAGE_PAV"] <- "PAV"
  df[df=="LINEAGE_CONSERVED"] <- "Conserved"
  
  df$host <- df_distance_info[df_distance_info$lineage_pav == TRUE | df_distance_info$lineage_conserved == TRUE,]$host
  
  df$gene_type_w_host <- paste(df$gene_type, df$host)
  
  df[df=="Conserved rice"] <- "MoO (Conserved)"
  df[df=="PAV rice"] <- "MoO (PAV)"
  df[df=="Conserved wheat"] <- "MoT (Conserved)"
  df[df=="PAV wheat"] <- "MoT (PAV)"
  
  df <- subset(df, select=-c(lineage_pav, lineage_conserved, gene_type, host))
  
  df$distance_up <- df_distance_info[df_distance_info$lineage_pav == TRUE | df_distance_info$lineage_conserved == TRUE,][[plot_columns[1]]]
  df$distance_down <- df_distance_info[df_distance_info$lineage_pav == TRUE | df_distance_info$lineage_conserved == TRUE,][[plot_columns[2]]]
  
  # this omits any genes that dont have known upstream OR downstream values
  df <- na.omit(df)
  
  df$distance_up <- log10(df$distance_up)
    
  df$distance_down <- log10(df$distance_down)
  
  ## currently this means that the median for all genes across wheat and rice blast is plotted on the 2d density plot
  
  x_int <- median(log10(df_distance_info[plot_columns[1]])[[1]], na.rm=TRUE)
  y_int <- median(log10(df_distance_info[plot_columns[2]])[[1]], na.rm=TRUE)
  
  ## plot 2d density plot
  ## new_scale_fill() allows different colors/plots for each category
  p <- ggplot(df, aes(x=distance_up, y=distance_down)) +
    stat_density_2d(data = ~ subset(., gene_type_w_host=="MoO (Conserved)"),aes(fill = ..level..), geom = "polygon", show.legend=FALSE) + # 2d density
    scale_fill_distiller(palette = "Greens", direction = 1, limits = c(0, 1)) +
    new_scale_fill() +
    stat_density_2d(data = ~ subset(., gene_type_w_host=="MoO (PAV)"),aes(fill = ..level..), geom = "polygon", show.legend=TRUE) + # 2d density
    scale_fill_distiller(palette = "Greys", direction = 1, limits = c(0, 1),
                         name = "Density") +
    new_scale_fill() +
    stat_density_2d(data = ~ subset(., gene_type_w_host=="MoT (Conserved)"),aes(fill = ..level..), geom = "polygon", 
                    show.legend=FALSE) + # 2d density
    scale_fill_distiller(palette = "Oranges", direction = 1, limits = c(0, 1)) +
    new_scale_fill() +
    stat_density_2d(data = ~ subset(., gene_type_w_host=="MoT (PAV)"),aes(fill = ..level..), geom = "polygon", 
                    show.legend=FALSE) + # 2d density
    scale_fill_distiller(palette = "Blues", direction = 1, limits = c(0, 1)) +
    geom_segment(aes(x=x_int,
                     xend=x_int,
                     y=-Inf,
                     yend=Inf), size = 0.5, linetype='dashed') +## draw median segments
    geom_segment(aes(x=-Inf,
                     xend=Inf,
                     y=y_int,
                     yend=y_int), size = 0.5, linetype='dashed') +
    scale_x_continuous(breaks=0:5, labels=c("0.001", "0.01", "0.1", "1", "10", "100"), limits = c(1,5)) + # logticks
    scale_y_continuous(breaks=0:5, labels=c("0.001", "0.01", "0.1", "1", "10", "100"), limits = c(1,5)) +
    xlab(paste("5' Distance to nearest ", axis_label, " (kbp)", sep ='')) +
    ylab(paste("3' Distance to nearest \n", axis_label, " (kbp)", sep ='')) +
    facet_grid(. ~ gene_type_w_host)+ # makes separate plots for each category
    theme_classic()+
      theme(axis.text=element_text(size=6), axis.title=element_text(size=8), 
        legend.title=element_text(size=8), legend.position = 'bottom', legend.text=element_text(size=6))+
    theme( strip.background = element_blank())+
    theme(legend.position="right")+
    theme(legend.key.size = unit(0.1, 'in'))+
    theme(legend.margin = margin(0, 0, 0, 0))

  ggsave(paste("facetgrid_",
             strsplit(plot_columns[1], '_')[[1]][1],
             '_',
             strsplit(plot_columns[1], '_')[[1]][2],
             '_3D_test.tiff',sep = ''), device = "tiff", plot = p, width = 6.5, height = 6.5/4, dpi=600)

}

```