---
title: "plot_phylogeny"
output: html_document
date: '2022-11-28'
---

```{r}
library(phytools)
library(ape)
```


```{r}
# read in new tree

tree = read.tree(file='Single_Copy_Orthologue_Sequences_msas_combined.trimmed.fasttree')

tree = root(tree, outgroup = "NI907",resolve.root=TRUE)

# prune NI907

tree <- drop.tip(tree,tree$tip.label[match("NI907", tree$tip.label)])

str_split_vector <- function(x, string){
  output_vector <- c()
  for ( item in x ) {
    output <- strsplit(item, string)[[1]][1]
    output_vector <- c(output_vector, output)
  }
  return(output_vector)
}

tree$tip.label <- str_split_vector(tree$tip.label, '_')

write.tree(tree, file='test_rooted_tree.txt')

```

```{r}

## node are 91 and 129

lineage_1_node <- 91

descendants <- getDescendants(tree, lineage_1_node)

descendants_lineage_1 <- descendants[descendants <= ncol(df)]

lineage_1_isolates <- tree$tip.label[descendants_lineage_1]

lineage_2_node <- 129

descendants <- getDescendants(tree, lineage_2_node)

descendants_lineage_2 <- descendants[descendants <= ncol(df)]

lineage_2_isolates <- tree$tip.label[descendants_lineage_2]

lineage_info <- data.frame(
  c(lineage_1_isolates, lineage_2_isolates),
  c(rep(1, length(lineage_1_isolates)), rep(2, length(lineage_2_isolates)))
)

colnames(lineage_info) <- c("isolate", "lineage")

output.file <- file('lineage_info.txt', "wb") ## to get unix line endings

write.table(lineage_info, file = output.file, quote = FALSE, col.names = FALSE, row.names = FALSE)

close(output.file)


```

```{r}
## read lineage_info

lineage_info <- data.frame(fread('lineage_info.txt'))

colnames(lineage_info) <- c('isolate', 'lineage')

lineage_info[nrow(lineage_info)+1,] <- c("GCA012979135.1", 0)

lineage_info$color <- NA

lineage_info$color[lineage_info$lineage==0] = 'purple'
lineage_info$color[lineage_info$lineage==1] = 'black'
lineage_info$color[lineage_info$lineage==2] = 'red'

lineage_info <- lineage_info[match(tree$tip.label, lineage_info$isolate),]

```



```{r}
pdf('wheat_blast_labeled_tree.pdf', width=6.5, height=6.5)
par(mar = c(1, 1, 1, 1))
plot(tree, type = "fan",tip.color=lineage_info$color,cex=0.5)
nodelabels(node=1:tree$Nnode+Ntip(tree),
    pie=cbind(as.numeric(tree$node.label),1-as.numeric(tree$node.label)),
    piecol=c("black","white"),cex=0.2)
add.scale.bar()
dev.off()
```
